package screens;

import classes.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.out;
import java.util.*;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {

    // Cria o vetor que armazena os logins dos alunos //
    public ArrayList<Aluno> alunos = new ArrayList<>();

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        btnEntrarLogin.setEnabled(false);
        btnCadastrarLogin.setEnabled(false);
        txtNomeLogin.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsuario = new javax.swing.JLabel();
        txtMatLogin = new javax.swing.JTextField();
        JSenha = new javax.swing.JLabel();
        txtSenhaLogin = new javax.swing.JPasswordField();
        JTituloLogin = new javax.swing.JLabel();
        btnEntrarLogin = new javax.swing.JButton();
        btnCadastrarLogin = new javax.swing.JButton();
        btnSairLogin = new javax.swing.JButton();
        txtNomeLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/university_cap_icon_32.png")).getImage());
        setResizable(false);

        jUsuario.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jUsuario.setText("Matrícula");

        txtMatLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatLoginActionPerformed(evt);
            }
        });

        JSenha.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        JSenha.setText("Senha");

        txtSenhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaLoginActionPerformed(evt);
            }
        });

        JTituloLogin.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        JTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTituloLogin.setText("CADASTRO/LOGIN");

        btnEntrarLogin.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnEntrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_enter_exit_open_icon_32.png"))); // NOI18N
        btnEntrarLogin.setText("Entrar");
        btnEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarLoginActionPerformed(evt);
            }
        });

        btnCadastrarLogin.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnCadastrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/livro_icon_32.png"))); // NOI18N
        btnCadastrarLogin.setText("Cadastrar");
        btnCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLoginActionPerformed(evt);
            }
        });

        btnSairLogin.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnSairLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_icon_32.png"))); // NOI18N
        btnSairLogin.setText("Sair");
        btnSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairLoginActionPerformed(evt);
            }
        });

        txtNomeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTituloLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jUsuario)
                        .addComponent(txtMatLogin)
                        .addComponent(JSenha)
                        .addComponent(txtSenhaLogin)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCadastrarLogin)
                            .addGap(18, 18, 18)
                            .addComponent(btnEntrarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSairLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtNomeLogin))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(JTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarLogin)
                    .addComponent(btnCadastrarLogin)
                    .addComponent(btnSairLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Checa se os campos estao preenchidos corretamente    
    private void txtMatLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatLoginActionPerformed
        checkFieldsActivation();
    }//GEN-LAST:event_txtMatLoginActionPerformed

    // Checa se os campos estao preenchidos corretamente    
    private void txtSenhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaLoginActionPerformed
        checkFieldsActivation();
    }//GEN-LAST:event_txtSenhaLoginActionPerformed

    // Termina o programa
    private void btnSairLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairLoginActionPerformed
        btnSairLogin.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnSairLoginActionPerformed

    // Cadastra o aluno utilizando a classe Aluno
    private void btnCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLoginActionPerformed
        
        int matricula = Integer.parseInt(txtMatLogin.getText());
        String senha = Arrays.toString(txtSenhaLogin.getPassword());
        String nome = txtNomeLogin.getText();
        Aluno aluno = new Aluno(nome, matricula, senha);
        
        int flag = 0;
        for(Aluno i : alunos){
            if(i.getMatricula() == aluno.getMatricula() || i.getNome().equals(nome))
                flag = 1;
        }
        
        // Se a flag for 0 o aluno é cadastrado no sistema
        if(flag == 0){
            alunos.add(aluno);
        } 
        
        // Cadastra os alunos usando arquivo de texto
        try {
            FileWriter fw = new FileWriter("files/resultados.txt", true);
            try (PrintWriter pw = new PrintWriter(fw)) {
                for(Aluno i : alunos){
                    pw.println(i.getNome());
                    pw.println(i.getMatricula());
                    pw.println(i.getSenha());
                }
            }
            JOptionPane.showMessageDialog(null, "Aluno cadastrado!");
        } catch (IOException e) {
            out.println("File not found");
        }
    }//GEN-LAST:event_btnCadastrarLoginActionPerformed

    // Entra na conta do aluno caso o aluno exista no sistema e caso a senha estiver correta
    private void btnEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarLoginActionPerformed
        
        int matricula = Integer.parseInt(txtMatLogin.getText());
        String senha = Arrays.toString(txtSenhaLogin.getPassword());
        String aux, nome = txtNomeLogin.getText();
        Aluno aluno = new Aluno(nome, matricula, senha);
        boolean flag = false;

        try {
            FileWriter fw = new FileWriter("files/login.txt");
            FileReader fr = new FileReader("files/resultados.txt");
            BufferedReader br = new BufferedReader(fr);
            
            // Entra na tela ira se o login for bem sucedido
            while((aux = br.readLine()) != null){
                
                boolean c0, c1, c2;
                c0 = aux.equals(aluno.getNome());
                c1 = br.readLine().equals(Integer.toString(aluno.getMatricula()));
                c2 = br.readLine().equals(aluno.getSenha());
                
                if(c0 && c1 && c2){
                    
                    // Salva o login do aluno
                    PrintWriter bf = new PrintWriter(fw);
                    
                    bf.println(aluno.getNome());
                    bf.println(aluno.getMatricula());
                    bf.println(aluno.getSenha());
                    bf.close();
                    
                    TelaIRA telaIra = new TelaIRA();
                    telaIra.setVisible(true);
                    setVisible(false);
                    flag = true;
                }
            }
        } catch (IOException e) {
            out.println("File not found");
        }
        
        // Caso flag continue zero, dados inseridos são incorretos
        if(!flag)
            JOptionPane.showMessageDialog(null, "Entrada inválida");
    }//GEN-LAST:event_btnEntrarLoginActionPerformed

    // Verifica o correto preenchimento dos campos
    private void txtNomeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeLoginActionPerformed
        checkFieldsActivation();
    }//GEN-LAST:event_txtNomeLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }
    
    // Verifica se todos os campos foram preenchidos. Se nao forem nulos, libera os botoes
    private void checkFieldsActivation(){
        if(txtMatLogin.getText().length() == 0 || txtSenhaLogin.getPassword().length == 0 || txtNomeLogin.getText().length() == 0){
            btnEntrarLogin.setEnabled(false);
            btnCadastrarLogin.setEnabled(false);
        } else {
            btnEntrarLogin.setEnabled(true);
            btnCadastrarLogin.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JSenha;
    private javax.swing.JLabel JTituloLogin;
    private javax.swing.JButton btnCadastrarLogin;
    private javax.swing.JButton btnEntrarLogin;
    private javax.swing.JButton btnSairLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JTextField txtMatLogin;
    private javax.swing.JTextField txtNomeLogin;
    private javax.swing.JPasswordField txtSenhaLogin;
    // End of variables declaration//GEN-END:variables
}